/**
 * HTML + CSS + JavaScript Exporter
 * 
 * Generates vanilla HTML with Tailwind CSS and vanilla JavaScript,
 * creating self-contained web components without framework dependencies.
 */

import type { ComponentSchema, FieldDefinition } from '@/lib/watsonx/types';
import type { 
  Exporter, 
  ExportFile, 
  CodeGenerationContext,
  ExportOptions 
} from '@/types/export';

export class HTMLExporter implements Exporter {
  format = 'html' as const;

  /**
   * Generate HTML files
   */
  async generate(context: CodeGenerationContext): Promise<ExportFile[]> {
    const files: ExportFile[] = [];
    const { schema, options, componentName, fileNameBase } = context;

    if (options.bundled) {
      // Single file with everything inline
      files.push({
        name: `${fileNameBase}.html`,
        content: this.generateSingleFile(schema, componentName, options),
        language: 'html',
        path: `${fileNameBase}.html`,
      });
    } else {
      // Separate HTML, CSS, and JS files
      files.push({
        name: `${fileNameBase}.html`,
        content: this.generateHTML(schema, componentName, fileNameBase),
        language: 'html',
        path: `${fileNameBase}.html`,
      });

      files.push({
        name: `${fileNameBase}.css`,
        content: this.generateCSS(schema, componentName),
        language: 'css',
        path: `${fileNameBase}.css`,
      });

      files.push({
        name: `${fileNameBase}.js`,
        content: this.generateJavaScript(schema, componentName, options),
        language: 'javascript',
        path: `${fileNameBase}.js`,
      });
    }

    // README
    if (options.includeReadme) {
      files.push({
        name: 'README.md',
        content: this.generateReadme(schema, componentName, fileNameBase),
        language: 'markdown',
        path: 'README.md',
      });
    }

    return files;
  }

  /**
   * Validate schema compatibility
   */
  validate(schema: ComponentSchema): { valid: boolean; errors?: string[] } {
    const errors: string[] = [];

    if (!schema.name) {
      errors.push('Component name is required');
    }

    return {
      valid: errors.length === 0,
      errors: errors.length > 0 ? errors : undefined,
    };
  }

  /**
   * Generate single self-contained HTML file
   */
  private generateSingleFile(
    schema: ComponentSchema,
    componentName: string,
    options: ExportOptions
  ): string {
    const includeComments = options.includeComments !== false;
    const hasForm = schema.fields && schema.fields.length > 0;

    let html = '<!DOCTYPE html>\n';
    html += '<html lang="en">\n';
    html += '<head>\n';
    html += '  <meta charset="UTF-8">\n';
    html += '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
    html += `  <title>${componentName}</title>\n`;
    
    if (includeComments) {
      html += `  <!-- Generated by NullRift UI on ${new Date().toLocaleDateString()} -->\n`;
    }
    
    // Tailwind CSS CDN
    html += '  <script src="https://cdn.tailwindcss.com"></script>\n';
    
    // Inline styles
    html += '  <style>\n';
    html += this.generateCSS(schema, componentName).split('\n').map(line => '    ' + line).join('\n');
    html += '\n  </style>\n';
    html += '</head>\n';
    html += '<body class="bg-gray-50 min-h-screen flex items-center justify-center p-4">\n';
    
    // Component HTML
    html += this.generateComponentHTML(schema, componentName, hasForm, 2);
    
    // Inline JavaScript
    html += '\n  <script>\n';
    html += this.generateJavaScript(schema, componentName, options).split('\n').map(line => '    ' + line).join('\n');
    html += '\n  </script>\n';
    html += '</body>\n';
    html += '</html>\n';

    return html;
  }

  /**
   * Generate separate HTML file
   */
  private generateHTML(
    schema: ComponentSchema,
    componentName: string,
    fileNameBase: string
  ): string {
    const hasForm = schema.fields && schema.fields.length > 0;

    let html = '<!DOCTYPE html>\n';
    html += '<html lang="en">\n';
    html += '<head>\n';
    html += '  <meta charset="UTF-8">\n';
    html += '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
    html += `  <title>${componentName}</title>\n`;
    html += '  <script src="https://cdn.tailwindcss.com"></script>\n';
    html += `  <link rel="stylesheet" href="${fileNameBase}.css">\n`;
    html += '</head>\n';
    html += '<body class="bg-gray-50 min-h-screen flex items-center justify-center p-4">\n';
    
    html += this.generateComponentHTML(schema, componentName, hasForm, 2);
    
    html += `\n  <script src="${fileNameBase}.js"></script>\n`;
    html += '</body>\n';
    html += '</html>\n';

    return html;
  }

  /**
   * Generate component HTML structure
   */
  private generateComponentHTML(
    schema: ComponentSchema,
    componentName: string,
    hasForm: boolean,
    indentLevel: number
  ): string {
    const indent = '  '.repeat(indentLevel);
    let html = '';

    html += `${indent}<div id="${this.toKebabCase(componentName)}" class="${this.generateClassName(schema)}">\n`;

    if (hasForm) {
      html += `${indent}  <form id="${this.toKebabCase(componentName)}-form" class="space-y-4">\n`;
      
      // Render fields
      (schema.fields || []).forEach(field => {
        html += this.generateFieldHTML(field, indentLevel + 2);
      });

      // Submit button
      html += `${indent}    <button\n`;
      html += `${indent}      type="submit"\n`;
      html += `${indent}      class="w-full px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"\n`;
      html += `${indent}    >\n`;
      html += `${indent}      Submit\n`;
      html += `${indent}    </button>\n`;
      html += `${indent}  </form>\n`;
    } else {
      html += `${indent}  <h2 class="text-2xl font-bold mb-4">${componentName}</h2>\n`;
      html += `${indent}  <p class="text-gray-600">${schema.description || 'Component content'}</p>\n`;
    }

    html += `${indent}</div>\n`;

    return html;
  }

  /**
   * Generate field HTML
   */
  private generateFieldHTML(field: FieldDefinition, indentLevel: number): string {
    const indent = '  '.repeat(indentLevel);
    let html = '';

    html += `${indent}<div class="space-y-2">\n`;
    html += `${indent}  <label for="${field.id}" class="block text-sm font-medium text-gray-700">\n`;
    html += `${indent}    ${field.label}${field.validation?.required ? ' *' : ''}\n`;
    html += `${indent}  </label>\n`;

    switch (field.type) {
      case 'textarea':
        html += `${indent}  <textarea\n`;
        html += `${indent}    id="${field.id}"\n`;
        html += `${indent}    name="${field.id}"\n`;
        html += `${indent}    placeholder="${field.placeholder || ''}"\n`;
        html += `${indent}    rows="4"\n`;
        html += `${indent}    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"\n`;
        html += `${indent}  ></textarea>\n`;
        break;

      case 'select':
        html += `${indent}  <select\n`;
        html += `${indent}    id="${field.id}"\n`;
        html += `${indent}    name="${field.id}"\n`;
        html += `${indent}    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"\n`;
        html += `${indent}  >\n`;
        html += `${indent}    <option value="">Select an option</option>\n`;
        (field.options || []).forEach(opt => {
          html += `${indent}    <option value="${opt.value}">${opt.label}</option>\n`;
        });
        html += `${indent}  </select>\n`;
        break;

      case 'checkbox':
        html += `${indent}  <div class="flex items-center">\n`;
        html += `${indent}    <input\n`;
        html += `${indent}      id="${field.id}"\n`;
        html += `${indent}      name="${field.id}"\n`;
        html += `${indent}      type="checkbox"\n`;
        html += `${indent}      class="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"\n`;
        html += `${indent}    />\n`;
        html += `${indent}  </div>\n`;
        break;

      case 'radio':
        html += `${indent}  <div class="space-y-2">\n`;
        (field.options || []).forEach(opt => {
          html += `${indent}    <div class="flex items-center">\n`;
          html += `${indent}      <input\n`;
          html += `${indent}        id="${field.id}-${opt.value}"\n`;
          html += `${indent}        name="${field.id}"\n`;
          html += `${indent}        type="radio"\n`;
          html += `${indent}        value="${opt.value}"\n`;
          html += `${indent}        class="w-4 h-4 text-blue-600 border-gray-300 focus:ring-blue-500"\n`;
          html += `${indent}      />\n`;
          html += `${indent}      <label for="${field.id}-${opt.value}" class="ml-2 text-sm">${opt.label}</label>\n`;
          html += `${indent}    </div>\n`;
        });
        html += `${indent}  </div>\n`;
        break;

      default: // input
        html += `${indent}  <input\n`;
        html += `${indent}    id="${field.id}"\n`;
        html += `${indent}    name="${field.id}"\n`;
        html += `${indent}    type="text"\n`;
        html += `${indent}    placeholder="${field.placeholder || ''}"\n`;
        html += `${indent}    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"\n`;
        html += `${indent}  />\n`;
    }

    html += `${indent}  <p id="${field.id}-error" class="text-sm text-red-600 hidden"></p>\n`;
    html += `${indent}</div>\n`;

    return html;
  }

  /**
   * Generate CSS
   */
  private generateCSS(schema: ComponentSchema, componentName: string): string {
    const primaryColor = schema.styling.primaryColor || '#3b82f6';
    const kebabName = this.toKebabCase(componentName);

    return `/* ${componentName} Styles */

:root {
  --primary-color: ${primaryColor};
  --border-radius: ${this.mapBorderRadius(schema.styling.borderRadius || 'md')};
}

#${kebabName} {
  /* Component-specific styles */
}

#${kebabName} .error {
  display: block;
  color: #dc2626;
  font-size: 0.875rem;
  margin-top: 0.25rem;
}

#${kebabName} input:focus,
#${kebabName} textarea:focus,
#${kebabName} select:focus {
  outline: 2px solid var(--primary-color);
  outline-offset: 2px;
}

/* Add custom styles here */
`;
  }

  /**
   * Generate JavaScript
   */
  private generateJavaScript(
    schema: ComponentSchema,
    componentName: string,
    options: ExportOptions
  ): string {
    const includeComments = options.includeComments !== false;
    const hasForm = schema.fields && schema.fields.length > 0;
    const kebabName = this.toKebabCase(componentName);

    let js = '';

    if (includeComments) {
      js += `/**\n * ${componentName} JavaScript\n * Generated by NullRift UI\n */\n\n`;
    }

    if (!hasForm) {
      js += `// Component initialization\n`;
      js += `console.log('${componentName} loaded');\n`;
      return js;
    }

    js += `(function() {\n`;
    js += `  'use strict';\n\n`;

    // Get form element
    js += `  const form = document.getElementById('${kebabName}-form');\n`;
    js += `  if (!form) return;\n\n`;

    // Validation functions
    (schema.fields || []).filter(f => f.validation).forEach(field => {
      js += this.generateValidationFunction(field);
    });

    // Clear error function
    js += `  function clearError(fieldId) {\n`;
    js += `    const errorEl = document.getElementById(fieldId + '-error');\n`;
    js += `    if (errorEl) {\n`;
    js += `      errorEl.textContent = '';\n`;
    js += `      errorEl.classList.add('hidden');\n`;
    js += `    }\n`;
    js += `  }\n\n`;

    // Show error function
    js += `  function showError(fieldId, message) {\n`;
    js += `    const errorEl = document.getElementById(fieldId + '-error');\n`;
    js += `    if (errorEl) {\n`;
    js += `      errorEl.textContent = message;\n`;
    js += `      errorEl.classList.remove('hidden');\n`;
    js += `    }\n`;
    js += `  }\n\n`;

    // Add input listeners to clear errors
    js += `  // Clear errors on input\n`;
    (schema.fields || []).forEach(field => {
      js += `  const ${field.id}Input = document.getElementById('${field.id}');\n`;
      js += `  if (${field.id}Input) {\n`;
      js += `    ${field.id}Input.addEventListener('input', () => clearError('${field.id}'));\n`;
      js += `  }\n`;
    });
    js += `\n`;

    // Form submit handler
    js += `  form.addEventListener('submit', function(e) {\n`;
    js += `    e.preventDefault();\n\n`;
    js += `    // Clear all errors\n`;
    (schema.fields || []).forEach(field => {
      js += `    clearError('${field.id}');\n`;
    });
    js += `\n`;

    js += `    // Validate all fields\n`;
    js += `    let hasErrors = false;\n`;
    (schema.fields || []).filter(f => f.validation).forEach(field => {
      js += `    const ${field.id}Value = ${field.id}Input.${field.type === 'checkbox' ? 'checked' : 'value'};\n`;
      js += `    const ${field.id}Error = validate${this.toPascalCase(field.id)}(${field.id}Value);\n`;
      js += `    if (${field.id}Error) {\n`;
      js += `      showError('${field.id}', ${field.id}Error);\n`;
      js += `      hasErrors = true;\n`;
      js += `    }\n`;
    });
    js += `\n`;

    js += `    if (hasErrors) return;\n\n`;

    js += `    // Get form data\n`;
    js += `    const formData = new FormData(form);\n`;
    js += `    const data = Object.fromEntries(formData.entries());\n\n`;

    js += `    // Submit form\n`;
    js += `    console.log('Form submitted:', data);\n`;
    js += `    // Add your submission logic here\n`;
    js += `  });\n`;

    js += `})();\n`;

    return js;
  }

  /**
   * Generate validation function
   */
  private generateValidationFunction(field: FieldDefinition): string {
    const validation = field.validation!;
    const funcName = `validate${this.toPascalCase(field.id)}`;

    let func = `  function ${funcName}(value) {\n`;

    if (validation.required) {
      if (field.type === 'checkbox') {
        func += `    if (!value) return '${validation.message || 'This field is required'}';\n`;
      } else {
        func += `    if (!value || value.trim() === '') return '${validation.message || 'This field is required'}';\n`;
      }
    }

    if (validation.minLength) {
      func += `    if (value.length < ${validation.minLength}) return 'Minimum length is ${validation.minLength} characters';\n`;
    }

    if (validation.maxLength) {
      func += `    if (value.length > ${validation.maxLength}) return 'Maximum length is ${validation.maxLength} characters';\n`;
    }

    if (validation.pattern) {
      func += `    if (!/${validation.pattern}/.test(value)) return '${validation.message || 'Invalid format'}';\n`;
    }

    func += `    return null;\n`;
    func += `  }\n\n`;

    return func;
  }

  /**
   * Generate README
   */
  private generateReadme(
    schema: ComponentSchema,
    componentName: string,
    fileNameBase: string
  ): string {
    return `# ${componentName}

${schema.description || 'Generated HTML component'}

## Usage

Simply open \`${fileNameBase}.html\` in a web browser.

### With a Web Server

\`\`\`bash
# Using Python
python -m http.server 8000

# Using Node.js
npx serve

# Using PHP
php -S localhost:8000
\`\`\`

Then navigate to \`http://localhost:8000/${fileNameBase}.html\`

## Files

- **${fileNameBase}.html** - Main HTML structure
- **${fileNameBase}.css** - Component styles
- **${fileNameBase}.js** - Interactive functionality

## Dependencies

This component uses Tailwind CSS via CDN. No build process required!

## Generated by NullRift UI

This component was generated by [NullRift UI](https://nullrift.com) on ${new Date().toLocaleDateString()}.
`;
  }

  // Helper methods
  private generateClassName(schema: ComponentSchema): string {
    const classes: string[] = ['w-full', 'max-w-md', 'mx-auto', 'p-6'];
    
    if (schema.styling.theme === 'dark') {
      classes.push('bg-gray-900', 'text-white');
    } else {
      classes.push('bg-white', 'text-gray-900');
    }
    
    classes.push(`rounded-${schema.styling.borderRadius || 'lg'}`);
    classes.push('shadow-lg');
    
    return classes.join(' ');
  }

  private mapBorderRadius(radius: string): string {
    const radiusMap: Record<string, string> = {
      none: '0',
      sm: '0.125rem',
      md: '0.375rem',
      lg: '0.5rem',
      xl: '0.75rem',
      '2xl': '1rem',
      full: '9999px',
    };
    return radiusMap[radius] || '0.375rem';
  }

  private toKebabCase(str: string): string {
    return str
      .replace(/([a-z])([A-Z])/g, '$1-$2')
      .replace(/[\s_]+/g, '-')
      .toLowerCase();
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
      .replace(/^(.)/, (_, c) => c.toUpperCase());
  }
}

// Made with Bob