/**
 * React + TypeScript Exporter
 * 
 * Generates production-ready React components with TypeScript,
 * including types, tests, and Storybook stories.
 */

import {
  type ComponentSchema,
  type FieldDefinition,
  DEFAULT_SUBMIT_BUTTON_LABEL,
} from '@/lib/watsonx/types';
import { resolveSubmitButtonPresentation } from '@/lib/tuning/submit-button-style';
import { SUBMIT_BUTTON_LAYER_ID, getEffectiveLayerOrder } from '@/lib/tuning/layer-order';
import type { 
  Exporter, 
  ExportFile, 
  CodeGenerationContext,
  ExportOptions 
} from '@/types/export';
import { CodeBuilder } from '@/lib/generator/code-builder';

export class ReactExporter implements Exporter {
  format = 'react-ts' as const;
  private codeBuilder = new CodeBuilder();

  /**
   * Generate React component files
   */
  async generate(context: CodeGenerationContext): Promise<ExportFile[]> {
    const files: ExportFile[] = [];
    const { schema, options, componentName, fileNameBase } = context;

    // Main component file
    files.push({
      name: `${fileNameBase}.tsx`,
      content: this.generateComponent(schema, componentName, options),
      language: 'typescript',
      path: `src/components/${fileNameBase}.tsx`,
    });

    // Type definitions file (if separate types requested)
    if (options.includeTypes && !options.bundled) {
      files.push({
        name: `${fileNameBase}.types.ts`,
        content: this.generateTypes(schema, componentName),
        language: 'typescript',
        path: `src/components/${fileNameBase}.types.ts`,
      });
    }

    // Test file
    if (options.includeTests) {
      files.push({
        name: `${fileNameBase}.test.tsx`,
        content: this.generateTests(schema, componentName, fileNameBase),
        language: 'typescript',
        path: `src/components/__tests__/${fileNameBase}.test.tsx`,
      });
    }

    // Storybook story
    if (options.includeStorybook) {
      files.push({
        name: `${fileNameBase}.stories.tsx`,
        content: this.generateStory(schema, componentName, fileNameBase),
        language: 'typescript',
        path: `src/components/${fileNameBase}.stories.tsx`,
      });
    }

    // README
    if (options.includeReadme) {
      files.push({
        name: 'README.md',
        content: this.generateReadme(schema, componentName, fileNameBase),
        language: 'markdown',
        path: 'README.md',
      });
    }

    // Package.json
    if (options.includePackageJson) {
      files.push({
        name: 'package.json',
        content: this.generatePackageJson(componentName, fileNameBase),
        language: 'json',
        path: 'package.json',
      });
    }

    return files;
  }

  /**
   * Validate schema compatibility
   */
  validate(schema: ComponentSchema): { valid: boolean; errors?: string[] } {
    const errors: string[] = [];

    if (!schema.name) {
      errors.push('Component name is required');
    }

    if (!schema.fields && !schema.props) {
      errors.push('Component must have either fields or props');
    }

    return {
      valid: errors.length === 0,
      errors: errors.length > 0 ? errors : undefined,
    };
  }

  /**
   * Generate main component file
   */
  private generateComponent(
    schema: ComponentSchema,
    componentName: string,
    options: ExportOptions
  ): string {
    const hasForm = schema.fields && schema.fields.length > 0;
    const includeComments = options.includeComments !== false;

    let code = '';

    // File header comment
    if (includeComments) {
      code += `/**
 * ${componentName}
 * 
 * ${schema.description || 'Generated component'}
 * 
 * @generated by NullRift UI
 * @date ${new Date().toISOString()}
 */

`;
    }

    // Imports
    code += this.generateImports(schema, hasForm);
    code += '\n\n';

    // Types (inline if bundled)
    if (options.bundled || !options.includeTypes) {
      code += this.generateTypes(schema, componentName);
      code += '\n\n';
    } else {
      code += `import type { ${componentName}Props } from './${this.toKebabCase(componentName)}.types';\n\n`;
    }

    // Component
    code += this.generateComponentBody(schema, componentName, hasForm, includeComments);

    return this.formatCode(code);
  }

  /**
   * Generate imports
   */
  private generateImports(schema: ComponentSchema, hasForm: boolean): string {
    const imports: string[] = [];

    // React imports
    const reactImports = ['React'];
    if (hasForm || schema.state) {
      reactImports.push('useState');
    }
    if (hasForm) {
      reactImports.push('FormEvent');
    }
    imports.push(`import { ${reactImports.join(', ')} } from 'react';`);

    // Icon imports (if needed)
    const needsIcons = schema.fields?.some(f => 
      f.type === 'checkbox' || f.type === 'radio'
    );
    if (needsIcons) {
      imports.push(`import { Check, X, AlertCircle } from 'lucide-react';`);
    }

    return imports.join('\n');
  }

  /**
   * Generate TypeScript types
   */
  private generateTypes(schema: ComponentSchema, componentName: string): string {
    let types = '';

    // Props interface
    types += `export interface ${componentName}Props {\n`;
    
    if (schema.props && schema.props.length > 0) {
      schema.props.forEach(prop => {
        if (prop.description) {
          types += `  /** ${prop.description} */\n`;
        }
        const optional = prop.required ? '' : '?';
        types += `  ${prop.name}${optional}: ${this.mapPropType(prop.type)};\n`;
      });
    } else {
      types += `  /** Additional CSS classes */\n`;
      types += `  className?: string;\n`;
    }
    
    types += `}\n`;

    // Form data interface (if form component)
    if (schema.fields && schema.fields.length > 0) {
      types += `\n`;
      types += `export interface ${componentName}FormData {\n`;
      schema.fields.forEach(field => {
        const optional = field.validation?.required ? '' : '?';
        const type = this.mapFieldType(field.type);
        types += `  ${field.id}${optional}: ${type};\n`;
      });
      types += `}\n`;

      // Form errors interface
      types += `\n`;
      types += `export interface ${componentName}FormErrors {\n`;
      schema.fields.forEach(field => {
        types += `  ${field.id}?: string;\n`;
      });
      types += `}\n`;
    }

    return types;
  }

  /**
   * Generate component body
   */
  private generateComponentBody(
    schema: ComponentSchema,
    componentName: string,
    hasForm: boolean,
    includeComments: boolean
  ): string {
    if (hasForm) {
      return this.generateFormComponent(schema, componentName, includeComments);
    }
    return this.generateSimpleComponent(schema, componentName, includeComments);
  }

  /**
   * Generate form component
   */
  private generateFormComponent(
    schema: ComponentSchema,
    componentName: string,
    includeComments: boolean
  ): string {
    const fields = schema.fields || [];
    
    let code = '';
    
    if (includeComments) {
      code += `/**\n * ${componentName} component\n */\n`;
    }
    
    code += `export function ${componentName}(props: ${componentName}Props) {\n`;
    
    // State initialization
    code += `  const [formData, setFormData] = useState<${componentName}FormData>({\n`;
    fields.forEach(field => {
      const defaultValue = this.getFieldDefaultValue(field);
      code += `    ${field.id}: ${defaultValue},\n`;
    });
    code += `  });\n\n`;
    
    code += `  const [errors, setErrors] = useState<${componentName}FormErrors>({});\n`;
    code += `  const [isSubmitting, setIsSubmitting] = useState(false);\n\n`;
    
    // Validation functions
    fields.filter(f => f.validation).forEach(field => {
      code += this.generateValidationFunction(field);
    });
    
    // Handle change
    code += `  const handleChange = (fieldId: keyof ${componentName}FormData, value: any) => {\n`;
    code += `    setFormData(prev => ({ ...prev, [fieldId]: value }));\n`;
    code += `    // Clear error when user starts typing\n`;
    code += `    if (errors[fieldId]) {\n`;
    code += `      setErrors(prev => ({ ...prev, [fieldId]: undefined }));\n`;
    code += `    }\n`;
    code += `  };\n\n`;
    
    // Handle submit
    code += `  const handleSubmit = async (e: FormEvent) => {\n`;
    code += `    e.preventDefault();\n`;
    code += `    setIsSubmitting(true);\n\n`;
    code += `    // Validate all fields\n`;
    code += `    const newErrors: ${componentName}FormErrors = {};\n`;
    fields.filter(f => f.validation).forEach(field => {
      code += `    const ${field.id}Error = validate${this.toPascalCase(field.id)}(formData.${field.id});\n`;
      code += `    if (${field.id}Error) newErrors.${field.id} = ${field.id}Error;\n`;
    });
    code += `\n    setErrors(newErrors);\n\n`;
    code += `    if (Object.keys(newErrors).length > 0) {\n`;
    code += `      setIsSubmitting(false);\n`;
    code += `      return;\n`;
    code += `    }\n\n`;
    code += `    // Submit form\n`;
    code += `    try {\n`;
    code += `      console.log('Form submitted:', formData);\n`;
    code += `      // Add your submission logic here\n`;
    code += `    } catch (error) {\n`;
    code += `      console.error('Submission error:', error);\n`;
    code += `    } finally {\n`;
    code += `      setIsSubmitting(false);\n`;
    code += `    }\n`;
    code += `  };\n\n`;
    
    // Render
    code += `  return (\n`;
    code += `    <div className="${this.generateClassName(schema)}">\n`;
    code += `      <form onSubmit={handleSubmit} className="space-y-4">\n`;
    
    const idleSubmitLabel = JSON.stringify(
      schema.submitButtonLabel?.trim() || DEFAULT_SUBMIT_BUTTON_LABEL
    );

    const submitPres = resolveSubmitButtonPresentation(schema.styling);
    const submitClassLiteral = JSON.stringify(submitPres.className);
    const submitStyleLiteral = JSON.stringify(submitPres.style);

    const submitButtonCode =
      `        <button\n` +
      `          type="submit"\n` +
      `          disabled={isSubmitting}\n` +
      `          className={${submitClassLiteral}}\n` +
      `          style={${submitStyleLiteral}}\n` +
      `        >\n` +
      `          {isSubmitting ? 'Submitting...' : ${idleSubmitLabel}}\n` +
      `        </button>\n`;

    const layerOrder = getEffectiveLayerOrder(schema);
    layerOrder.forEach((token) => {
      if (token === SUBMIT_BUTTON_LAYER_ID) {
        code += submitButtonCode;
        return;
      }
      const field = schema.fields.find((f) => f.id === token);
      if (field) {
        code += this.generateFieldJSX(field, 4);
      }
    });

    code += `      </form>\n`;
    code += `    </div>\n`;
    code += `  );\n`;
    code += `}\n`;
    
    return code;
  }

  /**
   * Generate simple component (non-form)
   */
  private generateSimpleComponent(
    schema: ComponentSchema,
    componentName: string,
    includeComments: boolean
  ): string {
    let code = '';
    
    if (includeComments) {
      code += `/**\n * ${componentName} component\n */\n`;
    }
    
    code += `export function ${componentName}(props: ${componentName}Props) {\n`;
    code += `  return (\n`;
    code += `    <div className="${this.generateClassName(schema)}">\n`;
    code += `      <h2 className="text-2xl font-bold mb-4">${componentName}</h2>\n`;
    code += `      <p className="text-gray-600">${schema.description || 'Component content'}</p>\n`;
    code += `    </div>\n`;
    code += `  );\n`;
    code += `}\n`;
    
    return code;
  }

  /**
   * Generate validation function for a field
   */
  private generateValidationFunction(field: FieldDefinition): string {
    const validation = field.validation!;
    const funcName = `validate${this.toPascalCase(field.id)}`;
    
    let code = `  const ${funcName} = (value: any): string | undefined => {\n`;
    
    if (validation.required) {
      if (field.type === 'checkbox') {
        code += `    if (!value) return '${validation.message || 'This field is required'}';\n`;
      } else {
        code += `    if (!value || value.trim() === '') return '${validation.message || 'This field is required'}';\n`;
      }
    }
    
    if (validation.minLength) {
      code += `    if (value.length < ${validation.minLength}) return 'Minimum length is ${validation.minLength} characters';\n`;
    }
    
    if (validation.maxLength) {
      code += `    if (value.length > ${validation.maxLength}) return 'Maximum length is ${validation.maxLength} characters';\n`;
    }
    
    if (validation.pattern) {
      code += `    if (!/${validation.pattern}/.test(value)) return '${validation.message || 'Invalid format'}';\n`;
    }
    
    code += `    return undefined;\n`;
    code += `  };\n\n`;
    
    return code;
  }

  /**
   * Generate field JSX
   */
  private generateFieldJSX(field: FieldDefinition, indent: number): string {
    const spaces = ' '.repeat(indent * 2);
    let jsx = '';
    
    jsx += `${spaces}<div className="space-y-2">\n`;
    jsx += `${spaces}  <label htmlFor="${field.id}" className="block text-sm font-medium text-gray-700">\n`;
    jsx += `${spaces}    ${field.label}${field.validation?.required ? ' *' : ''}\n`;
    jsx += `${spaces}  </label>\n`;
    
    switch (field.type) {
      case 'textarea':
        jsx += `${spaces}  <textarea\n`;
        jsx += `${spaces}    id="${field.id}"\n`;
        jsx += `${spaces}    value={formData.${field.id}}\n`;
        jsx += `${spaces}    onChange={(e) => handleChange('${field.id}', e.target.value)}\n`;
        jsx += `${spaces}    placeholder="${field.placeholder || ''}"\n`;
        jsx += `${spaces}    rows={4}\n`;
        jsx += `${spaces}    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"\n`;
        jsx += `${spaces}  />\n`;
        break;
        
      case 'select':
        jsx += `${spaces}  <select\n`;
        jsx += `${spaces}    id="${field.id}"\n`;
        jsx += `${spaces}    value={formData.${field.id}}\n`;
        jsx += `${spaces}    onChange={(e) => handleChange('${field.id}', e.target.value)}\n`;
        jsx += `${spaces}    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"\n`;
        jsx += `${spaces}  >\n`;
        jsx += `${spaces}    <option value="">Select an option</option>\n`;
        (field.options || []).forEach(opt => {
          jsx += `${spaces}    <option value="${opt.value}">${opt.label}</option>\n`;
        });
        jsx += `${spaces}  </select>\n`;
        break;
        
      case 'checkbox':
        jsx += `${spaces}  <div className="flex items-center">\n`;
        jsx += `${spaces}    <input\n`;
        jsx += `${spaces}      id="${field.id}"\n`;
        jsx += `${spaces}      type="checkbox"\n`;
        jsx += `${spaces}      checked={formData.${field.id}}\n`;
        jsx += `${spaces}      onChange={(e) => handleChange('${field.id}', e.target.checked)}\n`;
        jsx += `${spaces}      className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"\n`;
        jsx += `${spaces}    />\n`;
        jsx += `${spaces}  </div>\n`;
        break;
        
      default: // input
        jsx += `${spaces}  <input\n`;
        jsx += `${spaces}    id="${field.id}"\n`;
        jsx += `${spaces}    type="text"\n`;
        jsx += `${spaces}    value={formData.${field.id}}\n`;
        jsx += `${spaces}    onChange={(e) => handleChange('${field.id}', e.target.value)}\n`;
        jsx += `${spaces}    placeholder="${field.placeholder || ''}"\n`;
        jsx += `${spaces}    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"\n`;
        jsx += `${spaces}  />\n`;
    }
    
    jsx += `${spaces}  {errors.${field.id} && (\n`;
    jsx += `${spaces}    <p className="text-sm text-red-600 flex items-center gap-1">\n`;
    jsx += `${spaces}      <AlertCircle className="w-4 h-4" />\n`;
    jsx += `${spaces}      {errors.${field.id}}\n`;
    jsx += `${spaces}    </p>\n`;
    jsx += `${spaces}  )}\n`;
    jsx += `${spaces}</div>\n`;
    
    return jsx;
  }

  /**
   * Generate test file
   */
  private generateTests(
    schema: ComponentSchema,
    componentName: string,
    fileNameBase: string
  ): string {
    return `import { render, screen, fireEvent } from '@testing-library/react';
import { ${componentName} } from '../${fileNameBase}';

describe('${componentName}', () => {
  it('renders without crashing', () => {
    render(<${componentName} />);
  });

  it('displays the component', () => {
    render(<${componentName} />);
    expect(screen.getByRole('form')).toBeInTheDocument();
  });

  ${schema.fields?.map(field => `
  it('handles ${field.id} input', () => {
    render(<${componentName} />);
    const input = screen.getByLabelText('${field.label}');
    fireEvent.change(input, { target: { value: 'test value' } });
    expect(input).toHaveValue('test value');
  });`).join('\n') || ''}

  it('validates required fields on submit', async () => {
    render(<${componentName} />);
    const submitButton = screen.getByRole('button', { name: /submit/i });
    fireEvent.click(submitButton);
    
    ${schema.fields?.filter(f => f.validation?.required).map(field => `
    expect(await screen.findByText(/required/i)).toBeInTheDocument();`).join('') || ''}
  });
});
`;
  }

  /**
   * Generate Storybook story
   */
  private generateStory(
    schema: ComponentSchema,
    componentName: string,
    fileNameBase: string
  ): string {
    return `import type { Meta, StoryObj } from '@storybook/react';
import { ${componentName} } from './${fileNameBase}';

const meta: Meta<typeof ${componentName}> = {
  title: 'Components/${componentName}',
  component: ${componentName},
  tags: ['autodocs'],
  argTypes: {
    // Add argTypes here
  },
};

export default meta;
type Story = StoryObj<typeof ${componentName}>;

export const Default: Story = {
  args: {
    // Add default props here
  },
};

export const WithData: Story = {
  args: {
    // Add props with data here
  },
};
`;
  }

  /**
   * Generate README
   */
  private generateReadme(
    schema: ComponentSchema,
    componentName: string,
    fileNameBase: string
  ): string {
    return `# ${componentName}

${schema.description || 'Generated component'}

## Installation

\`\`\`bash
npm install react react-dom
\`\`\`

## Usage

\`\`\`tsx
import { ${componentName} } from './${fileNameBase}';

function App() {
  return <${componentName} />;
}
\`\`\`

## Props

${schema.props?.map(prop => `- **${prop.name}** (${prop.type})${prop.required ? ' *required*' : ''}: ${prop.description || ''}`).join('\n') || 'No props'}

## Generated by NullRift UI

This component was generated by [NullRift UI](https://nullrift.com) on ${new Date().toLocaleDateString()}.
`;
  }

  /**
   * Generate package.json
   */
  private generatePackageJson(componentName: string, fileNameBase: string): string {
    return JSON.stringify({
      name: fileNameBase,
      version: '1.0.0',
      description: `${componentName} component`,
      main: `src/components/${fileNameBase}.tsx`,
      scripts: {
        test: 'jest',
        build: 'tsc',
      },
      dependencies: {
        react: '^18.2.0',
        'react-dom': '^18.2.0',
        'lucide-react': '^0.263.1',
      },
      devDependencies: {
        '@types/react': '^18.2.0',
        '@types/react-dom': '^18.2.0',
        typescript: '^5.0.0',
        '@testing-library/react': '^14.0.0',
        '@testing-library/jest-dom': '^6.0.0',
        jest: '^29.0.0',
      },
    }, null, 2);
  }

  // Helper methods
  private mapPropType(type: string): string {
    const typeMap: Record<string, string> = {
      string: 'string',
      number: 'number',
      boolean: 'boolean',
      object: 'Record<string, any>',
      array: 'any[]',
      function: '(...args: any[]) => void',
    };
    return typeMap[type] || 'any';
  }

  private mapFieldType(type: string): string {
    const typeMap: Record<string, string> = {
      input: 'string',
      textarea: 'string',
      select: 'string',
      checkbox: 'boolean',
      radio: 'string',
      date: 'string',
      file: 'File | null',
    };
    return typeMap[type] || 'string';
  }

  private getFieldDefaultValue(field: FieldDefinition): string {
    switch (field.type) {
      case 'checkbox':
        return 'false';
      case 'file':
        return 'null';
      default:
        return "''";
    }
  }

  private generateClassName(schema: ComponentSchema): string {
    const classes: string[] = ['w-full', 'max-w-md', 'mx-auto', 'p-6'];
    
    if (schema.styling.theme === 'dark') {
      classes.push('bg-gray-900', 'text-white');
    } else {
      classes.push('bg-white', 'text-gray-900');
    }
    
    classes.push(`rounded-${schema.styling.borderRadius || 'lg'}`);
    classes.push('shadow-lg');
    
    return classes.join(' ');
  }

  private formatCode(code: string): string {
    // Basic formatting - remove excessive newlines
    return code.replace(/\n{3,}/g, '\n\n').trim();
  }

  private toKebabCase(str: string): string {
    return str
      .replace(/([a-z])([A-Z])/g, '$1-$2')
      .replace(/[\s_]+/g, '-')
      .toLowerCase();
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
      .replace(/^(.)/, (_, c) => c.toUpperCase());
  }
}

// Made with Bob