/**
 * Vue 3 + TypeScript Exporter
 * 
 * Generates Vue 3 Single File Components (SFC) with Composition API,
 * TypeScript support, and proper reactive state management.
 */

import {
  type ComponentSchema,
  type FieldDefinition,
  DEFAULT_SUBMIT_BUTTON_LABEL,
} from '@/lib/watsonx/types';
import { resolveSubmitButtonPresentation } from '@/lib/tuning/submit-button-style';
import { SUBMIT_BUTTON_LAYER_ID, getEffectiveLayerOrder } from '@/lib/tuning/layer-order';
import type { 
  Exporter, 
  ExportFile, 
  CodeGenerationContext,
  ExportOptions 
} from '@/types/export';

export class VueExporter implements Exporter {
  format = 'vue' as const;

  /**
   * Generate Vue component files
   */
  async generate(context: CodeGenerationContext): Promise<ExportFile[]> {
    const files: ExportFile[] = [];
    const { schema, options, componentName, fileNameBase } = context;

    // Main component file (.vue)
    files.push({
      name: `${fileNameBase}.vue`,
      content: this.generateComponent(schema, componentName, options),
      language: 'vue',
      path: `src/components/${fileNameBase}.vue`,
    });

    // Type definitions (if separate types requested)
    if (options.includeTypes && !options.bundled) {
      files.push({
        name: `${fileNameBase}.types.ts`,
        content: this.generateTypes(schema, componentName),
        language: 'typescript',
        path: `src/components/${fileNameBase}.types.ts`,
      });
    }

    // Test file
    if (options.includeTests) {
      files.push({
        name: `${fileNameBase}.spec.ts`,
        content: this.generateTests(schema, componentName, fileNameBase),
        language: 'typescript',
        path: `src/components/__tests__/${fileNameBase}.spec.ts`,
      });
    }

    // Storybook story
    if (options.includeStorybook) {
      files.push({
        name: `${fileNameBase}.stories.ts`,
        content: this.generateStory(schema, componentName, fileNameBase),
        language: 'typescript',
        path: `src/components/${fileNameBase}.stories.ts`,
      });
    }

    // README
    if (options.includeReadme) {
      files.push({
        name: 'README.md',
        content: this.generateReadme(schema, componentName, fileNameBase),
        language: 'markdown',
        path: 'README.md',
      });
    }

    // Package.json
    if (options.includePackageJson) {
      files.push({
        name: 'package.json',
        content: this.generatePackageJson(componentName, fileNameBase),
        language: 'json',
        path: 'package.json',
      });
    }

    return files;
  }

  /**
   * Validate schema compatibility
   */
  validate(schema: ComponentSchema): { valid: boolean; errors?: string[] } {
    const errors: string[] = [];

    if (!schema.name) {
      errors.push('Component name is required');
    }

    return {
      valid: errors.length === 0,
      errors: errors.length > 0 ? errors : undefined,
    };
  }

  /**
   * Generate Vue SFC
   */
  private generateComponent(
    schema: ComponentSchema,
    componentName: string,
    options: ExportOptions
  ): string {
    const hasForm = schema.fields && schema.fields.length > 0;
    const includeComments = options.includeComments !== false;

    let sfc = '';

    // Template section
    sfc += '<template>\n';
    sfc += this.generateTemplate(schema, hasForm);
    sfc += '</template>\n\n';

    // Script section
    sfc += '<script setup lang="ts">\n';
    if (includeComments) {
      sfc += `/**\n * ${componentName}\n * \n * ${schema.description || 'Generated component'}\n * \n * @generated by NullRift UI\n */\n\n`;
    }
    sfc += this.generateScript(schema, componentName, hasForm, options);
    sfc += '</script>\n\n';

    // Style section
    sfc += '<style scoped>\n';
    sfc += this.generateStyles(schema);
    sfc += '</style>\n';

    return sfc;
  }

  /**
   * Generate template section
   */
  private generateTemplate(schema: ComponentSchema, hasForm: boolean): string {
    let template = '';
    const indent = '  ';
    const componentName = schema.name;

    template += `${indent}<div :class="containerClasses">\n`;

    if (hasForm) {
      template += `${indent}  <form @submit.prevent="handleSubmit" class="space-y-4">\n`;

      const idleSubmitLabel = schema.submitButtonLabel?.trim() || DEFAULT_SUBMIT_BUTTON_LABEL;
      const submitButtonTemplate =
        `${indent}    <button\n` +
        `${indent}      type="submit"\n` +
        `${indent}      :disabled="isSubmitting"\n` +
        `${indent}      :class="submitButtonClass"\n` +
        `${indent}      :style="submitButtonStyle"\n` +
        `${indent}    >\n` +
        `${indent}      {{ isSubmitting ? 'Submitting...' : ${JSON.stringify(idleSubmitLabel)} }}\n` +
        `${indent}    </button>\n`;

      getEffectiveLayerOrder(schema).forEach((token) => {
        if (token === SUBMIT_BUTTON_LAYER_ID) {
          template += submitButtonTemplate;
          return;
        }
        const field = (schema.fields || []).find((f) => f.id === token);
        if (field) template += this.generateFieldTemplate(field, 4);
      });

      template += `${indent}  </form>\n`;
    } else {
      template += `${indent}  <h2 class="text-2xl font-bold mb-4">${componentName}</h2>\n`;
      template += `${indent}  <p class="text-gray-600">${schema.description || 'Component content'}</p>\n`;
    }

    template += `${indent}</div>\n`;

    return template;
  }

  /**
   * Generate field template
   */
  private generateFieldTemplate(field: FieldDefinition, indentLevel: number): string {
    const indent = '  '.repeat(indentLevel);
    let template = '';

    template += `${indent}<div class="space-y-2">\n`;
    template += `${indent}  <label :for="'${field.id}'" class="block text-sm font-medium text-gray-700">\n`;
    template += `${indent}    ${field.label}${field.validation?.required ? ' *' : ''}\n`;
    template += `${indent}  </label>\n`;

    switch (field.type) {
      case 'textarea':
        template += `${indent}  <textarea\n`;
        template += `${indent}    id="${field.id}"\n`;
        template += `${indent}    v-model="formData.${field.id}"\n`;
        template += `${indent}    placeholder="${field.placeholder || ''}"\n`;
        template += `${indent}    rows="4"\n`;
        template += `${indent}    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"\n`;
        template += `${indent}  />\n`;
        break;

      case 'select':
        template += `${indent}  <select\n`;
        template += `${indent}    id="${field.id}"\n`;
        template += `${indent}    v-model="formData.${field.id}"\n`;
        template += `${indent}    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"\n`;
        template += `${indent}  >\n`;
        template += `${indent}    <option value="">Select an option</option>\n`;
        (field.options || []).forEach(opt => {
          template += `${indent}    <option value="${opt.value}">${opt.label}</option>\n`;
        });
        template += `${indent}  </select>\n`;
        break;

      case 'checkbox':
        template += `${indent}  <div class="flex items-center">\n`;
        template += `${indent}    <input\n`;
        template += `${indent}      id="${field.id}"\n`;
        template += `${indent}      type="checkbox"\n`;
        template += `${indent}      v-model="formData.${field.id}"\n`;
        template += `${indent}      class="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"\n`;
        template += `${indent}    />\n`;
        template += `${indent}  </div>\n`;
        break;

      case 'radio':
        template += `${indent}  <div class="space-y-2">\n`;
        (field.options || []).forEach(opt => {
          template += `${indent}    <div class="flex items-center">\n`;
          template += `${indent}      <input\n`;
          template += `${indent}        id="${field.id}-${opt.value}"\n`;
          template += `${indent}        type="radio"\n`;
          template += `${indent}        v-model="formData.${field.id}"\n`;
          template += `${indent}        value="${opt.value}"\n`;
          template += `${indent}        class="w-4 h-4 text-blue-600 border-gray-300 focus:ring-blue-500"\n`;
          template += `${indent}      />\n`;
          template += `${indent}      <label :for="'${field.id}-${opt.value}'" class="ml-2 text-sm">${opt.label}</label>\n`;
          template += `${indent}    </div>\n`;
        });
        template += `${indent}  </div>\n`;
        break;

      default: // input
        template += `${indent}  <input\n`;
        template += `${indent}    id="${field.id}"\n`;
        template += `${indent}    type="text"\n`;
        template += `${indent}    v-model="formData.${field.id}"\n`;
        template += `${indent}    placeholder="${field.placeholder || ''}"\n`;
        template += `${indent}    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"\n`;
        template += `${indent}  />\n`;
    }

    template += `${indent}  <p v-if="errors.${field.id}" class="text-sm text-red-600">\n`;
    template += `${indent}    {{ errors.${field.id} }}\n`;
    template += `${indent}  </p>\n`;
    template += `${indent}</div>\n`;

    return template;
  }

  /**
   * Generate script section
   */
  private generateScript(
    schema: ComponentSchema,
    componentName: string,
    hasForm: boolean,
    options: ExportOptions
  ): string {
    let script = '';

    // Imports
    script += `import { ref, reactive, computed } from 'vue';\n`;
    
    if (options.includeTypes && !options.bundled) {
      script += `import type { ${componentName}Props, ${componentName}FormData, ${componentName}FormErrors } from './${this.toKebabCase(componentName)}.types';\n`;
    }
    script += '\n';

    // Types (inline if bundled)
    if (options.bundled || !options.includeTypes) {
      script += this.generateTypes(schema, componentName);
      script += '\n';
    }

    // Props
    script += this.generateProps(schema);
    script += '\n';

    if (hasForm) {
      // Form state
      script += this.generateFormState(schema);
      script += '\n';

      // Validation functions
      (schema.fields || []).filter(f => f.validation).forEach(field => {
        script += this.generateValidationFunction(field);
      });

      // Submit handler
      script += this.generateSubmitHandler(schema);
      script += '\n';
      script += this.generateSubmitButtonStyleConstants(schema);
    }

    // Computed properties
    script += this.generateComputedProperties(schema);

    return script;
  }

  /**
   * Generate TypeScript types
   */
  private generateTypes(schema: ComponentSchema, componentName: string): string {
    let types = '';

    // Props interface
    types += `export interface ${componentName}Props {\n`;
    if (schema.props && schema.props.length > 0) {
      schema.props.forEach(prop => {
        if (prop.description) {
          types += `  /** ${prop.description} */\n`;
        }
        const optional = prop.required ? '' : '?';
        types += `  ${prop.name}${optional}: ${this.mapPropType(prop.type)};\n`;
      });
    } else {
      types += `  /** Additional CSS classes */\n`;
      types += `  class?: string;\n`;
    }
    types += `}\n\n`;

    // Form data interface
    if (schema.fields && schema.fields.length > 0) {
      types += `export interface ${componentName}FormData {\n`;
      schema.fields.forEach(field => {
        const type = this.mapFieldType(field.type);
        types += `  ${field.id}: ${type};\n`;
      });
      types += `}\n\n`;

      // Form errors interface
      types += `export interface ${componentName}FormErrors {\n`;
      schema.fields.forEach(field => {
        types += `  ${field.id}?: string;\n`;
      });
      types += `}\n\n`;
    }

    return types;
  }

  /**
   * Generate props definition
   */
  private generateProps(schema: ComponentSchema): string {
    if (!schema.props || schema.props.length === 0) {
      return `const props = defineProps<${schema.name}Props>();\n`;
    }

    let props = `const props = withDefaults(defineProps<${schema.name}Props>(), {\n`;
    schema.props.forEach(prop => {
      if (prop.defaultValue !== undefined) {
        const value = typeof prop.defaultValue === 'string' 
          ? `'${prop.defaultValue}'` 
          : JSON.stringify(prop.defaultValue);
        props += `  ${prop.name}: ${value},\n`;
      }
    });
    props += `});\n`;

    return props;
  }

  /**
   * Generate form state
   */
  private generateFormState(schema: ComponentSchema): string {
    let state = '';

    // Form data
    state += `const formData = reactive<${schema.name}FormData>({\n`;
    (schema.fields || []).forEach(field => {
      const defaultValue = this.getFieldDefaultValue(field);
      state += `  ${field.id}: ${defaultValue},\n`;
    });
    state += `});\n\n`;

    // Errors
    state += `const errors = reactive<${schema.name}FormErrors>({});\n\n`;

    // Submitting state
    state += `const isSubmitting = ref(false);\n`;

    return state;
  }

  /**
   * Generate validation function
   */
  private generateValidationFunction(field: FieldDefinition): string {
    const validation = field.validation!;
    const funcName = `validate${this.toPascalCase(field.id)}`;

    let func = `const ${funcName} = (value: any): string | undefined => {\n`;

    if (validation.required) {
      if (field.type === 'checkbox') {
        func += `  if (!value) return '${validation.message || 'This field is required'}';\n`;
      } else {
        func += `  if (!value || value.trim() === '') return '${validation.message || 'This field is required'}';\n`;
      }
    }

    if (validation.minLength) {
      func += `  if (value.length < ${validation.minLength}) return 'Minimum length is ${validation.minLength} characters';\n`;
    }

    if (validation.maxLength) {
      func += `  if (value.length > ${validation.maxLength}) return 'Maximum length is ${validation.maxLength} characters';\n`;
    }

    if (validation.pattern) {
      func += `  if (!/${validation.pattern}/.test(value)) return '${validation.message || 'Invalid format'}';\n`;
    }

    func += `  return undefined;\n`;
    func += `};\n\n`;

    return func;
  }

  /**
   * Generate submit handler
   */
  private generateSubmitHandler(schema: ComponentSchema): string {
    let handler = `const handleSubmit = async () => {\n`;
    handler += `  isSubmitting.value = true;\n\n`;
    handler += `  // Clear previous errors\n`;
    handler += `  Object.keys(errors).forEach(key => {\n`;
    handler += `    delete errors[key as keyof ${schema.name}FormErrors];\n`;
    handler += `  });\n\n`;
    handler += `  // Validate all fields\n`;
    handler += `  let hasErrors = false;\n`;

    (schema.fields || []).filter(f => f.validation).forEach(field => {
      handler += `  const ${field.id}Error = validate${this.toPascalCase(field.id)}(formData.${field.id});\n`;
      handler += `  if (${field.id}Error) {\n`;
      handler += `    errors.${field.id} = ${field.id}Error;\n`;
      handler += `    hasErrors = true;\n`;
      handler += `  }\n`;
    });

    handler += `\n  if (hasErrors) {\n`;
    handler += `    isSubmitting.value = false;\n`;
    handler += `    return;\n`;
    handler += `  }\n\n`;
    handler += `  // Submit form\n`;
    handler += `  try {\n`;
    handler += `    console.log('Form submitted:', formData);\n`;
    handler += `    // Add your submission logic here\n`;
    handler += `  } catch (error) {\n`;
    handler += `    console.error('Submission error:', error);\n`;
    handler += `  } finally {\n`;
    handler += `    isSubmitting.value = false;\n`;
    handler += `  }\n`;
    handler += `};\n`;

    return handler;
  }

  /**
   * Static submit button class + inline colors from schema tuning.
   */
  private generateSubmitButtonStyleConstants(schema: ComponentSchema): string {
    const pres = resolveSubmitButtonPresentation(schema.styling);
    return `const submitButtonClass = ${JSON.stringify(pres.className)};
const submitButtonStyle = ${JSON.stringify(pres.style)};
`;
  }

  /**
   * Generate computed properties
   */
  private generateComputedProperties(schema: ComponentSchema): string {
    let computed = '\n';
    computed += `const containerClasses = computed(() => [\n`;
    computed += `  'w-full',\n`;
    computed += `  'max-w-md',\n`;
    computed += `  'mx-auto',\n`;
    computed += `  'p-6',\n`;
    
    if (schema.styling.theme === 'dark') {
      computed += `  'bg-gray-900',\n`;
      computed += `  'text-white',\n`;
    } else {
      computed += `  'bg-white',\n`;
      computed += `  'text-gray-900',\n`;
    }
    
    computed += `  'rounded-${schema.styling.borderRadius || 'lg'}',\n`;
    computed += `  'shadow-lg',\n`;
    computed += `  props.class,\n`;
    computed += `].filter(Boolean).join(' '));\n`;

    return computed;
  }

  /**
   * Generate styles section
   */
  private generateStyles(schema: ComponentSchema): string {
    const primaryColor = schema.styling.primaryColor || '#3b82f6';
    
    return `/* Component styles */
:root {
  --primary-color: ${primaryColor};
}

/* Add custom styles here */
`;
  }

  /**
   * Generate test file
   */
  private generateTests(
    schema: ComponentSchema,
    componentName: string,
    fileNameBase: string
  ): string {
    return `import { describe, it, expect } from 'vitest';
import { mount } from '@vue/test-utils';
import ${componentName} from '../${fileNameBase}.vue';

describe('${componentName}', () => {
  it('renders properly', () => {
    const wrapper = mount(${componentName});
    expect(wrapper.exists()).toBe(true);
  });

  ${schema.fields?.map(field => `
  it('handles ${field.id} input', async () => {
    const wrapper = mount(${componentName});
    const input = wrapper.find('#${field.id}');
    await input.setValue('test value');
    expect(input.element.value).toBe('test value');
  });`).join('\n') || ''}

  it('validates required fields on submit', async () => {
    const wrapper = mount(${componentName});
    await wrapper.find('form').trigger('submit');
    
    ${schema.fields?.filter(f => f.validation?.required).map(field => `
    expect(wrapper.text()).toContain('required');`).join('') || ''}
  });
});
`;
  }

  /**
   * Generate Storybook story
   */
  private generateStory(
    schema: ComponentSchema,
    componentName: string,
    fileNameBase: string
  ): string {
    return `import type { Meta, StoryObj } from '@storybook/vue3';
import ${componentName} from './${fileNameBase}.vue';

const meta: Meta<typeof ${componentName}> = {
  title: 'Components/${componentName}',
  component: ${componentName},
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof ${componentName}>;

export const Default: Story = {
  args: {},
};

export const WithData: Story = {
  args: {},
};
`;
  }

  /**
   * Generate README
   */
  private generateReadme(
    schema: ComponentSchema,
    componentName: string,
    fileNameBase: string
  ): string {
    return `# ${componentName}

${schema.description || 'Generated Vue 3 component'}

## Installation

\`\`\`bash
npm install vue
\`\`\`

## Usage

\`\`\`vue
<template>
  <${componentName} />
</template>

<script setup lang="ts">
import ${componentName} from './${fileNameBase}.vue';
</script>
\`\`\`

## Props

${schema.props?.map(prop => `- **${prop.name}** (${prop.type})${prop.required ? ' *required*' : ''}: ${prop.description || ''}`).join('\n') || 'No props'}

## Generated by NullRift UI

This component was generated by [NullRift UI](https://nullrift.com) on ${new Date().toLocaleDateString()}.
`;
  }

  /**
   * Generate package.json
   */
  private generatePackageJson(componentName: string, fileNameBase: string): string {
    return JSON.stringify({
      name: fileNameBase,
      version: '1.0.0',
      description: `${componentName} Vue component`,
      main: `src/components/${fileNameBase}.vue`,
      scripts: {
        dev: 'vite',
        build: 'vue-tsc && vite build',
        test: 'vitest',
      },
      dependencies: {
        vue: '^3.3.0',
      },
      devDependencies: {
        '@vitejs/plugin-vue': '^4.2.0',
        '@vue/test-utils': '^2.4.0',
        typescript: '^5.0.0',
        'vue-tsc': '^1.8.0',
        vite: '^4.4.0',
        vitest: '^0.34.0',
      },
    }, null, 2);
  }

  // Helper methods
  private mapPropType(type: string): string {
    const typeMap: Record<string, string> = {
      string: 'string',
      number: 'number',
      boolean: 'boolean',
      object: 'Record<string, any>',
      array: 'any[]',
      function: '(...args: any[]) => void',
    };
    return typeMap[type] || 'any';
  }

  private mapFieldType(type: string): string {
    const typeMap: Record<string, string> = {
      input: 'string',
      textarea: 'string',
      select: 'string',
      checkbox: 'boolean',
      radio: 'string',
      date: 'string',
      file: 'File | null',
    };
    return typeMap[type] || 'string';
  }

  private getFieldDefaultValue(field: FieldDefinition): string {
    switch (field.type) {
      case 'checkbox':
        return 'false';
      case 'file':
        return 'null';
      default:
        return "''";
    }
  }

  private toKebabCase(str: string): string {
    return str
      .replace(/([a-z])([A-Z])/g, '$1-$2')
      .replace(/[\s_]+/g, '-')
      .toLowerCase();
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
      .replace(/^(.)/, (_, c) => c.toUpperCase());
  }
}

// Made with Bob